name: "push tag"

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  pull_request_merge:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    timeout-minutes: 2

    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" =~ "chore/update-next-version" ]]; then
            echo "push tag release version"
          else
            echo "not needed"
            exit 0
          fi
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: main

      - name: Create next version
        run: |
          git branch
          tag_name="v$(sed -e 's/.*= \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/' ./version.txt)"
          git config user.name yochibot
          git config user.email no-replay-yochibot@github.com
          git tag $tag_name
          git push origin $tag_name
