name: "prepare after release process"

on:
  push:
    branches: [main]

jobs:
  pull_request_merge:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: develop

      - name: Create next version
        run: |
          git branch
          bash change.sh
          git config user.name yochibot
          git config user.email no-replay-yochibot@github.com
          git add .
          git commit -m "update version"

      - name: Create After Release Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: develop
          branch: chore/update-next-version
