name: "prepare after release process"

on:
  push:
    branches: [main]

jobs:
  pull_request_merge:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: develop

      - name: Create next version
        run: |
          echo 'hello'
          bash change.sh
          git diff

      # - name: Create After Release Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ steps.generate-token.outputs.token }}

      # - name: Fast Forword Merge
      #   uses: robotology/gh-action-nightly-merge@v1.4.0
      #   with:
      #     stable_branch: ${{ github.event.pull_request.head.ref }}
      #     development_branch: ${{ github.event.pull_request.base.ref }}
      #
      #     allow_ff: true
      #     ff_only: true
      #     allow_git_lfs: true
      #     allow_forks: false
      #
      #   env:
      #     GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
